### ISSUE TITLE
 require "jruby_mahout" LoadError: cannot load such file -- jruby_mahout

### ISSUE THREAD

**Issue by ManjunathGIT** [vasinov/jruby_mahout#5]
Jruby Mahout has been installed in my linux ruby environment,
Then entered an command 
> rails c
> require "jruby_mahout"
Resulted an error 
Loading development environment (Rails 4.0.2)
irb(main):001:0> require "jruby_mahout"
LoadError: cannot load such file -- jruby_mahout
        from /usr/local/lib/ruby/gems/2.1.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
        from /usr/local/lib/ruby/gems/2.1.0/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
Able to understand this problem
1. If i able to create jirb then jruby_mahout loading is fine
2. But my project is loaded as if in rails c or irb
3. As vasinov suggested i have specified
platform :jruby do
   gem "jruby_mahout",'0.2.0'
end
but many things like ~/.irbrc file editing. But resulting same error

**Comment by vasinov** [comment]
@ManjunathGIT looks like you are trying to load `jruby_mahout` in Ruby MRI instead of JRuby. It only works with JRuby because it uses a JVM library.
